---
host_list:
    - name: R2
      ip: 192.168.0.202
      platform: iosxr
      filter: >-
        <vrfs xmlns=http://cisco.com/ns/yang/Cisco-IOS-XR-infra-rsi-cfg></vrfs>
      edit_target: candidate
      operation: replace
    - name: R1
      ip: 192.168.0.201
      platform: ios
      filter: "<native><vrf></vrf></native>"
      edit_target: running
    