# List of Host on my network
# Structure Data Format, Collection of key value pairs
---
host_list:
    # each one is a dict, lista de diccionarios
    - name: R1
      ip: "192.168.0.201"
      vrf_cmd: "show running-config | section vrf_def"
      platform: ios
    - name: R2
      ip: "192.168.0.202"
      vrf_cmd: "show running-config vrf"
      platform: iosxr
      file_system: 'disk0' # file system key of ioscr
# file system sometimes can auto-discover sile systems.