# List of Host on my network
# Structure Data Format, Collection of key value pairs
---
host_list: # lista de diccionarios
    # each one is a dict
    - name: R1
      ip: "192.168.0.201"
      vrf_cmd: "show running-config | section vrf_def"
      platform: iosxr
    - name: R2
      ip: "192.168.0.202"
      vrf_cmd: "show running-config vrf"
      platform: ios