---
R1:
    hostname: 192.168.0.201
    groups:
        - ios
    data:
        vrfs:
            - name: "POLICE"
              description: "POLICE DEPARTMENT"
              rd: "65000:1"
              route_import:
                - "65000:1"
              route_export:
                - "65000:9"
            - name: "CHEMICAL"
              description: "CHEMICAL ENGINEERING FIRM"
              rd: "65000:2"
              route_import:
                - "65000:6"
              route_export:
                - "65000:2"
            - name: "CHEM_MGM"
              description: "CHEMICAL ENGINEERING MANAGER"
              rd: "65000:3"
              route_import:
                - "65000:4"
                - "65000:5"
              route_export:
                - "65000:3"
R3:
    hostname: 192.168.0.203
    groups:
        - ios
    data:
        vrfs:
            - name: "POLICE"
              description: "POLICE DEPARTMENT"
              rd: "65000:1"
              route_import:
                - "65000:1"
              route_export:
                - "65000:9"
            - name: "CHEMICAL"
              description: "CHEMICAL ENGINEERING FIRM"
              rd: "65000:2"
              route_import:
                - "65000:2"
                - "65000:7"
              route_export:
                - "65000:2"
                - "65000:4"